apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: melty-magic-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - melty-magic-store.20.44.59.222.nip.io  # Replace with your actual domain or nip.io mapping
