apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: melty-magic
  namespace: default
spec:
  gateways:
  - melty-magic-gateway
  hosts:
  - melty-magic-store.70.153.56.117.nip.io
  http:
  - route:
    - destination:
        host: melty-magic-store-service
        subset: v1
      weight: 80
    - destination:
        host: melty-magic-store-service
        subset: v2
      weight: 20
