apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: melty-magic
  namespace: default
spec:
  host: melty-magic-store-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
