apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: {{ .Release.Name }}-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx  # Using Nginx
  rules:
    - host: melty-magic-store.20.44.59.222.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80

